#!/bin/sh
echo "Which do you want?"
echo
echo "1)PDF to PNG"
echo "2)PDF to JPG"
echo
read  -p " -> " SELECT
echo "You selected ${SELECT}"

if [ "$SELECT" -eq "1" ]
then
	pdftoppm -png -r 300 $1 out
elif [ "$SELECT" -eq "2" ]
then
	pdftoppm -jpg -r 300 $1 out
else
		echo "Please Retery :-("
		sleep 5s
fi

exit
