#!/bin/bash

#Set video save path must include /
SAVE_PATH="~/Downloads/youtube-dl/"

function function_usage() {
		echo "Usage: $(basename ${0}) [OPTION]..."
		echo "No option	Show this message"
		echo "-h	Display help"
		echo "-a	Download audio only"
		echo "-U	Upgrade yt-dlp"
		echo "-v	Video download"
}

function function_a() {
		yt-dlp -f "bestaudio[ext=m4a]/best[ext=m4a]" --audio-format m4a  -P "$SAVE_PATH" $1
}

function funciton_v() {
		yt-dlp --console-title --write-subs --sub-langs "ja" --no-write-auto-subs -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" --video-format mp4 -P "$SAVE_PATH" $1
}

function_usage

read  -p " -> " SELECT
echo "You selected ${SELECT}"

case "$SELECT" in
	h)
		function_usage
		;;
	a)
		function_a
		;;
	U)
		pip install yt-dlp -U
		;;
	v)
		function_v
		;;
	*)
		function_usage
		exit 2
		;;
	\?)
		echo "Bad Option!!"
		function_usage
		exit 2
		;;
esac

echo "This command is $(basename ${0})"
