#!/bin/bash

#Set video save path must include /
cd ~/storage/downloads/youtube-dl/

function function_usage() {
		echo "Usage: $(basename ${0}) [OPTION]..."
		echo "No option	Show this message"
		echo "-h	Display help"
		echo "-a	Download audio only"
		echo "-U	Upgrade yt-dlp"
		echo "-v	Video download"
}

function_usage

read  -p " -> " SELECT
echo "You selected ${SELECT}"

case "$SELECT" in
	h)
		function_usage
		;;
	a)
		yt-dlp --console-title  -f "bestaudio[ext=m4a]/best[ext=m4a]" $2
		;;
	U)
		pip install yt-dlp -U
		;;
	v)
		yt-dlp --console-title -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" $2
		;;
	*)
		function_usage
		exit 2
		;;
	\?)
		echo "Bad Option!!"
		function_usage
		exit 2
		;;
esac

