#!/bin/bash
echo "Which do you want download?"
echo
echo "1)One Video"
echo "2)Playlist"
echo
read  -p " -> " SELECT
echo "You selected ${SELECT}"

if [ "$SELECT" -eq "1" ]
then
	youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]"  -o "~/storage/downloads/youtube-dl/%(title)s-%(channel)s.mp4" --no-mtime $1
elif [ "$SELECT" -eq "2" ]
then
	youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]"  -o "~/storage/downloads/youtube-dl/%(playlist_index)s_%(title)s-%(channel)s.mp4" --no-mtime $1
else
	echo "Please Retery :-("
fi

exit

